from typing import Any

import numpy as np
import numpy.typing as npt

# (int32 ceiling, int64 ceiling, float64 ceiling) -- see _core.max_energy_term()
max_energy_terms: tuple[int, int, float]

class GCO:
    num_sites: int
    num_labels: int
    width: int
    height: int
    is_grid: int
    is_float64: int
    dtype_code: int

    def __init__(
        self,
        num_sites: int,
        num_labels: int,
        dtype_code: int = ...,
        width: int = ...,
        height: int = ...,
    ) -> None: ...
    def destroy(self) -> None: ...
    def set_data_cost(self, cost: npt.NDArray[Any]) -> None: ...
    def set_data_cost_sparse(
        self, label: int, sites: npt.NDArray[np.int32], cost: npt.NDArray[Any]
    ) -> None: ...
    def set_smooth_cost(self, cost: npt.NDArray[Any]) -> None: ...
    def set_smooth_cost_vh(
        self, cost: npt.NDArray[Any], v_weights: npt.NDArray[Any], h_weights: npt.NDArray[Any]
    ) -> None: ...
    def set_neighbors(
        self,
        sites1: npt.NDArray[np.int32],
        sites2: npt.NDArray[np.int32],
        weights: npt.NDArray[Any] | None,
    ) -> None: ...
    def set_label_cost(self, cost: float) -> None: ...
    def set_label_cost_array(self, cost: npt.NDArray[Any]) -> None: ...
    def set_label_subset_cost(self, labels: npt.NDArray[np.int32], cost: float) -> None: ...
    def set_labeling(self, labeling: npt.NDArray[np.int32]) -> None: ...
    def get_labeling(self, out: npt.NDArray[np.int32], start: int = ...) -> None: ...
    def set_label_order_random(self, is_random: bool) -> None: ...
    def set_label_order(self, order: npt.NDArray[np.int32]) -> None: ...
    def set_verbosity(self, level: int) -> None: ...
    def expansion(self, max_cycles: int = ...) -> int | float: ...
    def swap(self, max_cycles: int = ...) -> int | float: ...
    def alpha_expansion(self, alpha: int) -> bool: ...
    def alpha_beta_swap(self, alpha: int, beta: int) -> None: ...
    def compute_energy(self) -> int | float: ...
    def data_energy(self) -> int | float: ...
    def smooth_energy(self) -> int | float: ...
    def label_energy(self) -> int | float: ...

class BKEnergy:
    num_vars: int
    dtype_code: int
    is_float64: int
    solved: int

    def __init__(self, num_vars: int, dtype_code: int = ...) -> None: ...
    def add_term1(self, cost: npt.NDArray[Any]) -> None: ...
    def add_term2(self, variables: npt.NDArray[np.int32], cost: npt.NDArray[Any]) -> None: ...
    def add_term3(self, variables: npt.NDArray[np.int32], cost: npt.NDArray[Any]) -> None: ...
    def add_constant(self, value: float) -> None: ...
    def minimize(self) -> int | float: ...
    def get_solution(self, out: npt.NDArray[np.uint8]) -> None: ...
    def destroy(self) -> None: ...

class BKGraph:
    num_nodes: int
    dtype_code: int
    is_float64: int
    flowed: int

    def __init__(
        self, num_nodes: int, dtype_code: int = ..., edge_capacity: int = ...
    ) -> None: ...
    def add_tweights(self, capacities: npt.NDArray[Any]) -> None: ...
    def add_edges(self, nodes: npt.NDArray[np.int32], capacities: npt.NDArray[Any]) -> None: ...
    def maxflow(self) -> int | float: ...
    def get_segments(self, out: npt.NDArray[np.uint8], default: int = ...) -> None: ...
    def destroy(self) -> None: ...
